### ISSUE TITLE
GE-SRTP default port

### ISSUE THREAD

**Issue by drsanwujiang** [Palatis/packet-ge-srtp#1]
The default port of GE-SRTP protocol is 18245, should it be changed?

**Comment by drsanwujiang** [comment]
The default port of GE-SRTP protocol is 18245, should it be changed?

**Comment by fzm0224** [comment]
GE-SRTP TCP的默认端口应该是18245吧。

**Comment by Palatis** [comment]
i don't know, i have no idea what the default port is.
60008 is what needed for my case.

feel free to submit a PR if you're sure that the default port is GE-SRTP is 18245, preferably with some (maybe official?) documentation (if there actually *is* any.)

**Comment by drsanwujiang** [comment]
Actually it is. Another interesting thing is that the hex string of 18245 is "47 45", which is the ASCII code of "GE"~
